# app/config/packages/security.yaml
security:
    encoders:
        App\Entity\User: bcrypt

    role_hierarchy:
        ROLE_READER: ROLE_USER
        ROLE_ADMIN: ROLE_READER

    providers:
        doctrine_user:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: doctrine_user
            json_login:
                check_path: /login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern:   ^/
            provider: doctrine_user
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
    - { path: ^/plane, roles: [ ROLE_ADMIN ] }
    - { path: ^/model, roles: [ ROLE_ADMIN ] }
    - { path: ^/crew, roles: [ ROLE_ADMIN ] }
    - { path: ^/compagny, roles: [ ROLE_ADMIN ] }
#        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/books, roles: [ ROLE_READER ] }
#        - { path: ^/, roles: [ ROLE_READER ] }

